using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class UIGamePanel : MonoBehaviour {

    public GameObject titleText;
    public GameObject returnButton;

	// Use this for initialization
	void Start () {

        returnButton.GetComponent<UnityEngine.UI.Button>().onClick.AddListener(onClickReturnButton);
	}

    void onClickReturnButton()
    {
        Debug.Log("C# -> onClickReturnButton");

        Debug.Log("C# -> CalcValue -> " + CalcValue(4, 5));

        UnityEngine.SceneManagement.SceneManager.LoadScene("LoginScene");
    }

    int CalcValue(int a, int b)
    {
        return a + b;
    }
}
